### ISSUE TITLE
m5stackplus show error time out

### ISSUE THREAD

**Issue by jangarga** [raomin/ESPAltherma#118]

**Comment by jangarga** [comment]
Good morning,

after 2 months working fine, now m5stackplus show error in photo in attached and on home assistant data from altherma arrived not in continuos mode, attached screen. can you help me with this issue?

**Comment by munzili** [comment]
Are you sure this is not a Network/Wifi issue?

I see some registers work. Does the Display show the same messages all the time (same messages when data correctly received from Home Assistant and also when not)?

**Comment by raomin** [comment]
0x15 0xea means that the Heat pump did not understand the query from ESPAltherma.
It's either because the protocol of the heat pump is too old (not your case as it worked before) see eg #74  
Or, most probably here, a misconnection of a wire, probably ground... Make sure all your connections are clean and well pushed. 
You can also restart your heat pump but I doubt it will change much...

**Comment by jangarga** [comment]
finally was network problem. thanks for support
