### ISSUE TITLE
Fix wifi mesh: failed

### ISSUE THREAD

**Issue by rayxxxxx** [raomin/ESPAltherma#271]
With the last version (fix wifi mesh)I have an error during compile code:
Compiling .pio/build/esp32/src/main.cpp.o
src/main.cpp: In function 'void setup_wifi()':
src/main.cpp:145:8: error: 'class WiFiClass' has no member named 'setScanMethod'
   WiFi.setScanMethod(WIFI_ALL_CHANNEL_SCAN);
        ^~~~~~~~~~~~~
src/main.cpp:146:8: error: 'class WiFiClass' has no member named 'setSortMethod'
   WiFi.setSortMethod(WIFI_CONNECT_AP_BY_SIGNAL);
        ^~~~~~~~~~~~~

**Comment by raomin** [comment]
It's probably because you still have an old arduino-esp32 platform.
Can you open a platformio terminal and launch an update?
`pio pkg update`
Or go to `PlatformIO Home > Platforms > Updates` and update Espressif 32. You should have version 6.1

Anyway, I fear this is not enough to solve the wifi mesh issue.
I'll probably rollback this one.
