### ISSUE TITLE
Integrate multiple boards MQTT and HomeAssistant

### ISSUE THREAD

**Issue by merinsTDL** [raomin/ESPAltherma#427]
Good day! 

I would like to monitor multiple Altherma units connected to the same HA and MQTT broker. 
Unfortunately, the current code hardcodes all MCUs connect to the same topic. 
I would like to introduce some variable that allows to set the unit name and then for each unit to split the data. 
Which would be the best solution to split them based on the unit?
1. To replace the MQTT topics based on unit name root i.e. <espaltherma>/LWT.
2. To add in the path the unit name i.e. espaltherma/<unit_name>/LWT.

**Comment by KindeG** [comment]
Hello,
what I did is to change the topics - and also I recommend the 2. solution.
you should change it in a few files, basically:
setup.h (if onetopic is used...)
main.cpp (log...)
mqtt.h (/ATTR & /LWT & all the sensor publishing)

This way you can really do the things. I also put it into telegraf & grafana, that's why I suggest to have the unit name as well to feed the parser an easier recognition.

**Comment by merinsTDL** [comment]
Thank you @KindeG for the suggestions! 
I will adjust it in this way!

**Comment by merinsTDL** [comment]
Closing as resolved.
